### ISSUE TITLE
Stop tracking generated files, OS junk

### ISSUE THREAD

**Issue by EvanFBC** [sm1th-/csvr#1]
You'll want to create a `.gitignore` file to tell git which files to ignore. You *only* want to track source code, so gems and your bin/ folder can be ignored. Additionally, .DS_Store is a metadata file that OS X creates, and should be ignored as well, as it's irrelevant to your source code.

A `.gitignore` file would look something like this:

```
*.gem
bin/

.DS_Store
```

Likewise, you don't want to include the imported SQLite db in your repository, nor your own stops.csv. So you could add these lines to your `.gitignore`:

```
stops.csv
*.db
```

Keep in mind that adding the lines to .gitignore [won't remove the files](http://gitready.com/beginner/2009/03/06/ignoring-doesnt-remove-a-file.html), just stops tracking them. So you'll want to otherwise delete the .gem files and bin/ from your repository.

And if you're already tracking a file, adding it to `.gitignore` after the fact won't stop tracking it. You need to use `git rm --cached` to remove the file from the repository (but not your filesystem).

More info: https://help.github.com/articles/ignoring-files/

**Comment by sm1th-** [comment]
Thanks! That makes life easier!

**Comment by sm1th-** [comment]
Ok - For the bin file, will removing this not also remove the command line? 
For example when I type in Terminal : $ csvr api 
Still a little confused about bin, I was under the impression it allowed me to run the gem from the command line

**Comment by EvanFBC** [comment]
Whoops! You're right about that!

**Comment by sm1th-** [comment]
Okay cool, I mean the bin file doesn't do shit now but it's good to know if I want to add some stuff there
